### ISSUE TITLE
百度云存储C++SDK怎样获取上传下载进度

### ISSUE THREAD

**Issue by uuuuu17171717** [Kontinuation/bce-cppsdk#1]
兄弟，百度云存储C++SDK怎样获取上传下载进度

**Comment by Kontinuation** [comment]
Most of the code in this repository is taken from the [official documentation](https://cloud.baidu.com/doc/BOS/s/Wjwvys6li), and there are no public interfaces for retrieving the progress of object downloading/uploading. You need to hack it on your own. Maybe [send_request](https://github.com/Kontinuation/bce-cppsdk/blob/master/src/bos/client_impl.cpp#L83) is a good starting point to work on.

Disclaimer: I am not the maintainer of the official BOS C++ SDK, I've only changed its build system for my own convenience.

**Comment by uuuuu17171717** [comment]
https://github.com/uuuuu17171717/huaweicloud-sdk-c-obs 挽尊

**Comment by uuuuu17171717** [comment]
https://github.com/uuuuu17171717/BaiduCloudCppSdk
